### ISSUE TITLE
Button do not decode `textColor` and `title`

### ISSUE THREAD

**Issue by phimage** [IBDecodable/IBDecodable#13]
The code in `Button`
```swift
   textColor:     try decodeValue(xml),
   title:              try decodeValue(xml),
```
I make this bug because of some analysing tool that I make
But I think maybe it is a false positive

**Comment by SD10** [comment]
Yes @phimage we need to remove these, they are leftover from when I was extracting this from IBLinter.

```xml
<state key=“normal” title=“REGISTER TO BID”>
    <color key=“titleColor” red=“0.0" green=“0.0” blue=“0.0" alpha=“1” colorSpace=“custom” customColorSpace=“sRGB”/>
    <color key=“titleShadowColor” red=“0.0” green=“0.0" blue=“0.0” alpha=“0.0" colorSpace=“custom” customColorSpace=“sRGB”/>
</state>
<state key=“disabled”>
    <color key=“titleColor” red=“0.64313725489999995” green=“0.64313725489999995" blue=“0.64313725489999995” alpha=“1" colorSpace=“custom” customColorSpace=“sRGB”/>
</state>
```

I think these things should be an array of `[State]` and inside it can have an array of `[Color]`:

**Comment by phimage** [comment]
Ok 
Then something
xml.byKey("textColor").flatMap(decodeValue)

**Comment by SD10** [comment]
```swift
var states: [State]

var titleColor: Color {
  return states.first(where: $0.key == "titleColor")
}
```
I'm thinking something like this. But the `titleColor` property is not necessary. Low priority. We can add those in an extension in IBLinter 🤔

**Comment by SD10** [comment]
I was trying to avoid having specific properties for attributes that's why I wanted to have an array or dictionary. It's a light-weight solution. We don't care if a `State` object is a `titleColor` or `highlightedColor`. We just throw them in an array. Then retrieve a specific item using a computed property 🤔 Let me know if you think this is not a good idea

**Comment by phimage** [comment]
I agree with you

**Comment by phimage** [comment]
I report modification from IBLinter. A `State` object.
