### ISSUE TITLE
Dictionary for all objects by id

### ISSUE THREAD

**Issue by kateinoigakukun** [IBDecodable/IBDecodable#30]
> Some other rules will need all objects by id in a dictionary, others by type (xml element name)

https://github.com/IBDecodable/IBDecodable/pull/24#issuecomment-383267128

We need this dictionary but I'm wondering how to implement it.

**Comment by phimage** [comment]
In storyboard document we could add a lazy instanciated variable.

Call a recursive function on all elements starting with the document 

To compute it we need to add a protocol to allow browsing, with a fonction that provide All children elements
For a doc, the scenes, etc...
For a scene, the view controller, etc...
For a view controller the root view, etc..
For a view the subviews, etc...
Etc...

—-

The other way, is too notify after decoding an object to a delegate which can agregate it
This delegate could be 
- a singleton 
- or passed in init 
...
- could be the parser class, or another user given objects

—- 

Have two elements with same id is an issue so we must be careful of that

**Comment by phimage** [comment]
@kateinoigakukun I made an object which browse the tree to put elements in map by id, type, etc...

https://github.com/IBDecodable/IBDecodable/blob/master/Tests/IBAnalyser.swift

I am not sure that could be in IBDecodable, so I add it in unit test
Similar object or functions could be added to IBLinter
