### ISSUE TITLE
CollectionViewCell content view has no id attribute

### ISSUE THREAD

**Issue by felginep** [IBDecodable/IBDecodable#48]
If I create a xib with only a collection view cell in it, I have the following structure:
```
<?xml version="1.0" encoding="UTF-8"?>
<document type="com.apple.InterfaceBuilder3.CocoaTouch.XIB" version="3.0" toolsVersion="14313.18" targetRuntime="iOS.CocoaTouch" propertyAccessControl="none" useAutolayout="YES" useTraitCollections="YES" useSafeAreas="YES" colorMatched="YES">
    <device id="retina4_7" orientation="portrait">
        <adaptation id="fullscreen"/>
    </device>
    <dependencies>
        <plugIn identifier="com.apple.InterfaceBuilder.IBCocoaTouchPlugin" version="14283.14"/>
        <capability name="Safe area layout guides" minToolsVersion="9.0"/>
        <capability name="documents saved in the Xcode 8 format" minToolsVersion="8.0"/>
    </dependencies>
    <objects>
        <placeholder placeholderIdentifier="IBFilesOwner" id="-1" userLabel="File's Owner" customClass="UIViewController"/>
        <placeholder placeholderIdentifier="IBFirstResponder" id="-2" customClass="UIResponder"/>
        <collectionViewCell opaque="NO" clipsSubviews="YES" multipleTouchEnabled="YES" contentMode="center" id="v5y-fv-StP">
            <rect key="frame" x="0.0" y="0.0" width="50" height="50"/>
            <autoresizingMask key="autoresizingMask" flexibleMaxX="YES" flexibleMaxY="YES"/>
            <view key="contentView" opaque="NO" clipsSubviews="YES" multipleTouchEnabled="YES" contentMode="center" insetsLayoutMarginsFromSafeArea="NO">
                <rect key="frame" x="0.0" y="0.0" width="50" height="50"/>
                <autoresizingMask key="autoresizingMask"/>
            </view>
            <viewLayoutGuide key="safeArea" id="Jkp-Kr-0cj"/>
        </collectionViewCell>
    </objects>
</document>
```

Note that the first subview of `collectionViewCell` has no identifier. For now, the `ViewProtocol` protocol makes `id` a requirement. 

What is the best way to handle this ?
- Turn `ViewProtocol.id` to `String?` ?
- Have a fallback value (i.e. `""`) ?

I guess the fallback value is the easiest one. I'll be happy to create a pull request, but I prefer to check with you first.

**Comment by kateinoigakukun** [comment]
Thank you for your contribution!
I guess `key="contentView"` is special case for `UICollectionViewCell` and extract like this is more better.
```swift
let contentView = try container.withAttributeElement(.key, "contentView")
```

**Comment by felginep** [comment]
I'm not sure to understand your solution.
The issue is not that it can't find the view, but that the view can't be decoded because of the `id` attribute missing.

In `View.decode(_:XMLIndexer)` I suggest this change:
```
return View(
-           id:  try container.attribute(of: .id),
+           id:  container.attributeIfPresent(of: .id) ?? "",
```

**Comment by phimage** [comment]
we have in collection view
`public let contentView: View`

maybe do
`public let contentView: CollectionContentView`

Then in CollectionView add a new struct CollectionContentView by copying view
except the `try container.attribute(of: .id)`that could repalce with ?? ""

So we do not edit the general `View` and keep test on id

**Comment by felginep** [comment]
Seems fine to me. I'll give it a try. Thanks !
